-- AlterEnum
ALTER TYPE "EmailTemplateType" ADD VALUE IF NOT EXISTS 'EVENT_UPDATE';
ALTER TYPE "EmailTemplateType" ADD VALUE IF NOT EXISTS 'EVENT_CANCELLED';
ALTER TYPE "EmailTemplateType" ADD VALUE IF NOT EXISTS 'CALL_TIME_UPDATE';
ALTER TYPE "EmailTemplateType" ADD VALUE IF NOT EXISTS 'CALL_TIME_CANCELLED';
